version: 0.0
os: linux
files:
  - source: dist/
    destination: /var/dashboard_frontend/
  - source: scripts/smartthings_dashboard.service
    destination: /etc/systemd/system/
  - source: scripts/start_app.sh
    destination: /var/dashboard_frontend/
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root