version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12.x
  build:
    commands:
      - npm install
      - npm build
artifacts:
  files:
    - dev-server.js
    - dist/*
    - appspec.yml
    - scripts/*
  discard-paths: no