version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
  build:
    commands:
      - npm install
      - npm run build
      - ls -l
      - cd dist/
      - ls -l
artifacts:
  files:
    - dev-server.js
    - dist/*
    - appspec.yml
    - scripts/*
  discard-paths: no