version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
  build:
    commands:
      - npm install
      - npm run build
      - 'NODE_ENV=production npm prune'
artifacts:
  files:
    - ./*
    - dist/**/*
    - appspec.yml
    - scripts/*
    - node_modules/**/*
  discard-paths: no